// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BackCine.Data.Entities;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int IdCliente { get; set; }

    public int IdFuncion { get; set; }

    public DateTime FechaReserva { get; set; }

    public int CantidadEntradas { get; set; }

    public int IdEstado { get; set; }

    public int? IdCompra { get; set; }

    public virtual ICollection<ButacasReservada> ButacasReservada { get; set; } = new List<ButacasReservada>();
    [JsonIgnore]
    public virtual Cliente IdClienteNavigation { get; set; }
    [JsonIgnore]
    public virtual Compra IdCompraNavigation { get; set; }
    [JsonIgnore]
    public virtual Funcione IdFuncionNavigation { get; set; }
}