// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace BackCine.Data.Entities;

public partial class Sala
{
    public int IdSala { get; set; }

    public int Capacidad { get; set; }

    public string Descripcion { get; set; }

    public int IdTipoSala { get; set; }

    public virtual ICollection<Funcione> Funciones { get; set; } = new List<Funcione>();
    [JsonIgnore]
    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}