// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BackCine.Data.Entities;

public partial class VisDetallesCompra
{
    public int IdCliente { get; set; }

    public string NombreCliente { get; set; }

    public DateTime FechaCompra { get; set; }

    public int ButacaReservada { get; set; }

    public string Sala { get; set; }

    public decimal? PrecioTotal { get; set; }
}