// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using BackCine.Data.Entities;

namespace BackCine.Data.Entities
{
    public partial class CineMaxContext
    {

        [DbFunction("f_fecha", "dbo")]
        public static string f_fecha(DateTime? fecha)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("f_hora", "dbo")]
        public static string f_hora()
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        [DbFunction("fn_butacas_disponibles", "dbo")]
        public static bool? fn_butacas_disponibles(int? id_funcion, int? id_butaca, int? id_sala)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
